# Generated by Django 5.1.3 on 2024-11-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='politician',
            name='Text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
