# Generated by Django 5.1.3 on 2024-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_alter_politician_image_alter_politician_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='politician_images/'),
        ),
    ]
