# Generated by Django 5.1.3 on 2024-11-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0003_alter_politician_image'),
        ('polls', '0009_election_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.election'),
        ),
    ]
