# Generated by Django 5.1.3 on 2024-11-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_text_question_question_text1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text1',
            new_name='question_text',
        ),
    ]
