# Generated by Django 5.1.3 on 2024-11-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_election'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='pub_date',
        ),
    ]
