# Generated by Django 5.1.3 on 2024-11-27 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_election_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
