# Generated by Django 5.1.3 on 2024-11-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
