# Generated by Django 5.1.3 on 2024-11-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='userid',
            new_name='user_name',
        ),
    ]
