# Generated by Django 5.1.3 on 2024-11-26 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0003_face_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='face_img',
            new_name='face_img_test',
        ),
        migrations.AddField(
            model_name='face',
            name='face_img_train',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
