# Generated by Django 5.1.3 on 2024-11-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facerec', '0004_rename_face_img_face_face_img_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face_img_test',
            field=models.ImageField(upload_to='face_images/test/'),
        ),
        migrations.AlterField(
            model_name='face',
            name='face_img_train',
            field=models.ImageField(upload_to='face_images/train/'),
        ),
    ]
